name: Publish npm package

on:
  push:
    branches:
      - main   # Run only on push to main branch

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20
        registry-url: https://registry.npmjs.org/

    - name: Authenticate npm
      run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

    - name: Install dependencies
      run: npm install

    - name: Bump version
      run: |
        npm version patch -m "ci: bump version to %s"

    - name: Publish package
      run: npm publish --access public

    - name: Push changes & tags
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git push origin main --tags
